### ISSUE TITLE
Support for multiple Uptime Kuma backends

### ISSUE THREAD

**Issue by volkankoc** [FZnachor/Uptime-Status#1]
I have several different uptime services, how can I connect them all?
ex:
http://uptime-kuma.local-1:3001
http://uptime-kuma.local-2:3001
http://uptime-kuma.local-3:3001
http://uptime-kuma.local-4:3001

**Comment by FZnachor** [comment]
Thank you for your feature suggestion. Support for multiple Uptime Kuma backends including failover mode was added in the last commit. See the updated `config.inc.php` file for more details.
